### ISSUE TITLE
ci: Need to fix or switch away from Travis CI

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-external-examples#158]
Example of current breakage:
https://travis-ci.com/RobotLocomotion/drake-external-examples

Jamie is saying that he may switch away to GitHub Actions or Azure Pipelines, possibly replacing Circle CI as well.

**Comment by EricCousineau-TRI** [comment]
This will happen after Jamie has vetted this in `underactuated`.

**Comment by jwnimmer-tri** [comment]
In the meantime, can we switch off the broken build so that PRs do not have false-positive build failures?

**Comment by jamiesnape** [comment]
As far as I can tell it is off now. Does not seem to be running on merge, at least.
