### ISSUE TITLE
Need to provide example of consuming CMake drake from catkin / ament

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-external-examples#163]
Relates to https://github.com/RobotLocomotion/drake/issues/12773

Steps:
- [x] #168 catkin
- [x] colcon
- [x] Run CI

**Comment by jamiesnape** [comment]
`colcon` rather than `ament` probably makes more sense for the future.

**Comment by EricCousineau-TRI** [comment]
Ah, well, I think it's using the `colcon` tools, but `ament_cmake` for specifying C++ builds?

**Comment by jamiesnape** [comment]
Exactly.

**Comment by jwnimmer-tri** [comment]
FYI see https://github.com/RobotLocomotion/ros-drake-vendor/issues/8.  Apparently hard-coding `/opt/drake` into our examples CMakeLists was a bad idea, and we're planning on ripping that out.
