### ISSUE TITLE
[Question] Ubuntu 16.04

### ISSUE THREAD

**Issue by MartinaRuocco** [RobotLocomotion/drake-external-examples#189]
Hi,
is there a way to modify the instructions to make them compatible with other versions of Ubuntu? 
I am working on Ubuntu 16.04

**Comment by jwnimmer-tri** [comment]
Drake v0.11.0 (https://drake.mit.edu/release_notes/v0.11.0.html) is the last revision of Drake that supports Ubuntu 16.04.  A co-temporal version of _this_ repository (2019-10-02), e.g., 87c9fad0e166e8480c4fa00880ab610ce4026df5 might be a good starting point.
