### ISSUE TITLE
[drake-bazel-installed] Python examples all fail to import pydrake

### ISSUE THREAD

**Issue by mposa** [RobotLocomotion/drake-external-examples#214]
Never mind! I did not realize that the code in this project is all explicitly for Ubuntu 18. Tweaking for 20.04 fixed the issue.

**Comment by jwnimmer-tri** [comment]
I'm curious to see if I can improve the documentation or error messages in this case.  I went to try to find the place where Ubuntu 18 was lurking, but didn't immediately see it.  Do you remember what part of the code the confusion came from?

**Comment by mposa** [comment]
In the WORKSPACE file:

https://github.com/RobotLocomotion/drake-external-examples/blob/be73cfe7567fcaa8ca103f4c0b7810d9076a430c/drake_bazel_installed/WORKSPACE#L62

**Comment by jwnimmer-tri** [comment]
Aha!  That is quite hidden; I missed it.  I'll open a PR to make it more clear.
