### ISSUE TITLE
[drake_cmake_installed] CMake error when make in release mode

### ISSUE THREAD

**Issue by Yingfan99327** [RobotLocomotion/drake-external-examples#231]
When I try to run make after I run cmake -DCMAKE_PREFIX_PATH=/opt/drake ../drake_cmake_installed I met some problems as follows:
/usr/bin/ld: warning: libgfortran.so.5, needed by /opt/drake/lib/libdrake.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libspdlog.so.1, needed by /opt/drake/lib/libdrake.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libamd.so.2, needed by /opt/drake/lib/libdrake.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libnlopt_cxx.so.0, needed by /opt/drake/lib/libdrake.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libipopt.so.1, needed by /opt/drake/lib/libdrake.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libdmumps_seq-5.2.1.so, needed by /opt/drake/lib/libdrake.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libClpSolver.so.1, needed by /opt/drake/lib/libdrake.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libClp.so.1, needed by /opt/drake/lib/libdrake.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libCoinUtils.so.3, needed by /opt/drake/lib/libdrake.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libGLEW.so.2.1, needed by /opt/drake/lib/libdrake.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libdouble-conversion.so.3, needed by /opt/drake/lib/libdrake.so, not found (try using -rpath or -rpath-link)
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_set_ftol_rel'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDeleteQueries'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_set_ftol_abs'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBindBuffer'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGenRenderbuffers'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBindBufferBase'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_set_maxtime'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_concat_string@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewEndTransformFeedback'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpSimplex::dual(int, int)'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_set_xtol_abs1'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const@GLIBCXX_3.4.26'
/opt/drake/lib/libdrake.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26'
/opt/drake/lib/libdrake.so: undefined reference to `ClpModel::setObjectiveOffset(double)'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetNamedRenderbufferParameteriv'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_add_inequality_constraint'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__GLEW_VERSION_3_2'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_destroy'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBufferData'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_st_read@GFORTRAN_8'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_st_close@GFORTRAN_8'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_set_upper_bounds'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_st_rewind@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUniform3fv'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewStencilOpSeparate'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_set_maxeval'
/opt/drake/lib/libdrake.so: undefined reference to `ClpModel::scaling(int)'
/opt/drake/lib/libdrake.so: undefined reference to `spdlog::pattern_formatter::pattern_formatter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, spdlog::pattern_time_type, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::_List::end() const@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUniformMatrix3fv'
/opt/drake/lib/libdrake.so: undefined reference to `vtable for Ipopt::OptionsList'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDeleteRenderbuffers'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewTexImage3D'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_set_min_objective'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::current_path[abi:cxx11]()@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetShaderiv'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewTransformFeedbackVaryings'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBindFragDataLocation'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__GLEW_ARB_texture_float'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDisableVertexAttribArray'
/opt/drake/lib/libdrake.so: undefined reference to `ClpSimplex::ClpSimplex(bool)'
/opt/drake/lib/libdrake.so: undefined reference to `ClpSimplex::~ClpSimplex()'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpSimplex::infeasibilityRay(bool) const'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__GLEW_ARB_transform_feedback3'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBlitFramebuffer'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBeginQuery'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_transfer_real@GFORTRAN_8'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpModel::setMaximumIterations(int)'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewFramebufferTexture2D'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_st_inquire@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUniform1f'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGenFramebuffers'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpSimplex::setColumnBounds(int, double, double)'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewClampColor'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_compare_string@GFORTRAN_8'
/opt/drake/lib/libdrake.so: undefined reference to `ClpSimplex::primal(int, int)'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDeleteProgram'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::_List::_List(std::filesystem::__cxx11::path::_List const&)@GLIBCXX_3.4.26'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_st_write_done@GFORTRAN_8'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetQueryObjectuiv'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_get_errmsg'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_set_xtol_rel'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGenVertexArrays'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetFramebufferAttachmentParameteriv'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpModel::addRow(int, int const*, double const*, double, double)'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::read_symlink(std::filesystem::__cxx11::path const&)@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewMapBufferRange'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewTexBuffer'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__GLEW_ARB_direct_state_access'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpSimplex::setRowBounds(int, double, double)'
//opt/drake/lib/libvtkIOCore-9.1.so.1: undefined reference to `double_conversion::DoubleToStringConverter::EcmaScriptConverter()'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__GLEW_ARB_gpu_shader5'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBeginTransformFeedback'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::lexically_normal() const@GLIBCXX_3.4.26'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_add_inequality_mconstraint'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDeleteVertexArrays'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewShaderSource'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetBufferPointerv'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_set_lower_bounds'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDeleteFramebuffers'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_transfer_real_write@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDeleteShader'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewCheckFramebufferStatus'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_st_write@GFORTRAN_8'
/opt/drake/lib/libdrake.so: undefined reference to `CoinMessageHandler::setLogLevel(int)'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewFramebufferRenderbuffer'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDrawBuffers'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetAttribLocation'
/opt/drake/lib/libdrake.so: undefined reference to `log2@GLIBC_2.29'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewQueryCounter'
/opt/drake/lib/libdrake.so: undefined reference to `pow@GLIBC_2.29'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__GLEW_ARB_instanced_arrays'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUniform1fv'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpModel::setPrimalTolerance(double)'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::absolute(std::filesystem::__cxx11::path const&)@GLIBCXX_3.4.26'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_transfer_integer@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDrawArraysInstancedARB'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewVertexAttribPointer'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::_M_append(std::basic_string_view<char, std::char_traits<char> >)@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBindVertexArray'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewEndQuery'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetQueryObjectiv'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::_List::_List()@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUseProgram'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_etime@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBindFramebuffer'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewEndQueryIndexed'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_transfer_character_write@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewFramebufferTexture3D'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_string_trim@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__GLEW_VERSION_3_1'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewRenderbufferStorage'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetUniformLocation'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpModel::writeMps(char const*, int, int, double) const'
/opt/drake/lib/libdrake.so: undefined reference to `vtable for Ipopt::RegisteredOption'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetProgramiv'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::replace_extension(std::filesystem::__cxx11::path const&)@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetShaderInfoLog'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUniform2iv'
/opt/drake/lib/libdrake.so: undefined reference to `exp@GLIBC_2.29'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_create'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUniform2fv'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGenBuffers'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpModel::setOptimizationDirection(double)'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpModel::setDualTolerance(double)'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::operator/=(std::filesystem::__cxx11::path const&)@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetQueryObjectui64v'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `glewGetErrorString'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::parent_path() const@GLIBCXX_3.4.26'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_add_equality_constraint'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUniformMatrix4fv'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGenerateMipmap'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_add_equality_mconstraint'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpModel::setMaximumSeconds(double)'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__GLEW_EXT_texture_filter_anisotropic'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewTexImage2DMultisample'
/opt/drake/lib/libdrake.so: undefined reference to `ClpModel::loadProblem(int, int, int const*, int const*, double const*, double const*, double const*, double const*, double const*, double const*, double const*)'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewCreateProgram'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBindRenderbuffer'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_st_read_done@GFORTRAN_8'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_set_munge'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_transfer_array@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDeleteBuffers'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::_List::_Impl_deleter::operator()(std::filesystem::__cxx11::path::_List::_Impl*) const@GLIBCXX_3.4.26'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpSimplex::setObjectiveCoefficient(int, double)'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewStencilFuncSeparate'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewCompileShader'
//opt/drake/lib/libdrake_ibex.so: undefined reference to `ClpSimplex::resize(int, int)'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_st_open@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewMapBuffer'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBlendEquationSeparate'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUniform1i'
/opt/drake/lib/libdrake.so: undefined reference to `vtable for Ipopt::RegisteredOptions'
/opt/drake/lib/libdrake.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewRenderbufferStorageMultisample'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const@GLIBCXX_3.4.26'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::equivalent(std::filesystem::__cxx11::path const&, std::filesystem::__cxx11::path const&)@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBeginQueryIndexed'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewVertexAttribDivisorARB'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_transfer_array_write@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewAttachShader'
/opt/drake/lib/libdrake.so: undefined reference to `IpoptApplicationFactory'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetProgramInfoLog'
/opt/drake/lib/libdrake.so: undefined reference to `log@GLIBC_2.29'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewLinkProgram'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUnmapBuffer'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUniform4fv'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_set_force_stop'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDrawRangeElements'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetRenderbufferParameteriv'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_transfer_character@GFORTRAN_8'
/opt/drake/lib/libdrake.so: undefined reference to `amd_order'
//opt/drake/lib/libvtkIOCore-9.1.so.1: undefined reference to `double_conversion::DoubleToStringConverter::ToShortestIeeeNumber(double, double_conversion::StringBuilder*, double_conversion::DoubleToStringConverter::DtoaMode) const'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_optimize'
/opt/drake/lib/libdrake.so: undefined reference to `std::runtime_error::operator=(std::runtime_error&&)@GLIBCXX_3.4.26'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewEnableVertexAttribArray'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_transfer_integer_write@GFORTRAN_8'
/opt/drake/lib/libdrake.so: undefined reference to `nlopt_get_dimension'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewUniform1iv'
/opt/drake/lib/libdrake.so: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()@GLIBCXX_3.4.26'
/opt/drake/lib/libdrake.so: undefined reference to `ClpModel::loadQuadraticObjective(int, int const*, int const*, double const*)'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewCreateShader'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetStringi'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_transfer_logical_write@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGenQueries'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDetachShader'
/opt/drake/lib/libdrake.so: undefined reference to `_gfortran_string_index@GFORTRAN_8'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewGetTextureLevelParameteriv'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewStencilMaskSeparate'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewActiveTexture'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewDrawElementsInstancedARB'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `glewInit'
//opt/drake/lib/libvtkRenderingOpenGL2-9.1.so.1: undefined reference to `__glewBlendFuncSeparate'
collect2: error: ld returned 1 exit status
src/find_resource/CMakeFiles/find_resource_example.dir/build.make:99: recipe for target 'src/find_resource/find_resource_example' failed
make[2]: *** [src/find_resource/find_resource_example] Error 1
CMakeFiles/Makefile2:1008: recipe for target 'src/find_resource/CMakeFiles/find_resource_example.dir/all' failed
make[1]: *** [src/find_resource/CMakeFiles/find_resource_example.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

How can I solve such error? I try to install drake on ubuntu18.04, I don't know whether that will influence my installation process? Thanks.

**Comment by jwnimmer-tri** [comment]
What version of Drake are you using?  As of [v1.2.0](https://drake.mit.edu/release_notes/v1.2.0.html), Drake does not support Ubuntu 18.04 anymore.

**Comment by Yingfan99327** [comment]
I guess I am trying to install drake of v1.3.0, so such error occurs mainly due to the version of the ubuntu system I use? I have to use ubuntu20.04, right?

**Comment by jwnimmer-tri** [comment]
Yes; here are the supported versions:

https://drake.mit.edu/installation.html
