### ISSUE TITLE
drake_bazel_external warnings about reproducibility

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake-external-examples#272]
While developing jenkins updates the job https://drake-jenkins.csail.mit.edu/job/RobotLocomotion/job/drake-external-examples/job/main/301/consoleFull says:

```
DEBUG: Rule 'drake' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "5d95cfd141662f42affe0cc50241b129b7a69ca0bcaae6b0ed180000e053c99d"
DEBUG: Repository drake instantiated at:
  /media/ephemeral0/ubuntu/workspace/ion_drake-external-examples_main/src/drake_bazel_external/WORKSPACE:32:13: in <toplevel>
Repository rule http_archive defined at:
  /media/ephemeral0/ubuntu/workspace/ion_drake-external-examples_main/_bazel_ubuntu/9a00cf05048ed9bdf126eba755fd527b/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
```

It's not clear to me if this is something that needs to be fixed or not.  Feel free to close without any fixes.  CC @jwnimmer-tri

**Comment by jwnimmer-tri** [comment]
This is typical behavior when using an unpinned dependency:

https://github.com/RobotLocomotion/drake-external-examples/blob/d538d621d8605253763b8e223f0f0ca96fb6bb23/drake_bazel_external/WORKSPACE#L5-L6
