### ISSUE TITLE
Where are the executables using drake_cmake_external??

### ISSUE THREAD

**Issue by xiao-wang007** [RobotLocomotion/drake-external-examples#273]
Hi 
This may be a silly question, but I cannot find the executables after build in cmake. 
In addition, where is the executable of the `simple_continuouse_time_system.cc`??
If using drake as external, do I just need to put everything under `app/`

Cheers

**Comment by jwnimmer-tri** [comment]
The README says to build it like this:

> To build all apps using CMake and Make:
>
> ```
> mkdir build
> cd build
> cmake ..
> make
> ```

Assuming you've done that, the binary is at `./drake_external_examples/apps/simple_continuous_time_system` (in other words, `drake-external-examples/drake_cmake_external/build/drake_external_examples/apps/simple_continuous_time_system`).

>  If using drake as external, do I just need to put everything under `app/`?

No.  You can use any directory names you want.

**Comment by xiao-wang007** [comment]
Great! Thanks.

**Comment by xiao-wang007** [comment]
Great, thanks!
