### ISSUE TITLE
Avoid handing out broken builds to users

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake-external-examples#74]
The https://github.com/RobotLocomotion/drake-external-examples/blob/master/drake_cmake_installed/README.md instructions point users to https://drake-packages.csail.mit.edu/drake/nightly/drake-latest-xenial.tar.gz.  However, it appears that even if the Nightly CI fails, the package is still uploaded and the "latest" link changed to use it?  That means users will see broken nightlies, which seems awful.

Is it easy to change the build to not bump the "latest", or to have a different "latest-passing" or something?  Or worst case for now just don't upload anything?

I just had a user try to use the broken nightly and have to ask for help.

**Comment by jwnimmer-tri** [comment]
Ah, I misunderstood the sequence of events.  Drake's CI publishes nightlies, and Shambhala tests against them.  So it's not a trivial fix.  I wonder if Shambhala can take over the `latest` bumping, or something.

(I guess really, we should have Shambhala in pre-merge anyway, which makes many things better.)

**Comment by jwnimmer-tri** [comment]
Or I guess the real problem is that Shambhala master assumes that its setup script is compatible with Drake nightlies, which means #61 is the real problem.  I guess the Drake nightly should publish an appropriately-compatible setup script itself.

**Comment by jamiesnape** [comment]
> I guess the Drake nightly should publish an appropriately-compatible setup script itself.

It is on my TODO list.

Until we have API stability and acceptance tests, we are not going to be able to guarantee that each successive night’s packages are compatible with each other. That is not unusual with nightly builds, though. The trouble is that we do not have releases yet.

**Comment by jwnimmer-tri** [comment]
Those are good points.

**Comment by jwnimmer-tri** [comment]
I think there's nothing left to do here.  We have releases, we publish setup scripts, and #61 tracks using the setup scripts for this CI.
