### ISSUE TITLE
Make meaningful PCL + Drake example

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-external-examples#91]
Per [discussion](https://github.com/RobotLocomotion/drake-shambhala/pull/76#issuecomment-364464026) in #76, the PCL + Drake example (and linking test) should show non-trivial functionality.

At present, this is blocked by the failure shown in #90.

\cc @jamiesnape

**Comment by jwnimmer-tri** [comment]
Per #179, I think this is moot now.  Please reopen if I'm mistaken.
